SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('[EXT].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER_LOAD]') IS NOT NULL 
DROP PROCEDURE [EXT].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER_LOAD]
GO

CREATE PROC [EXT].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER_LOAD] AS
/*===========================================================================
 PROCEDURE NAME:  [EXT].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER_LOAD]
 DESCRIPTION:     SP to load Brand Hierarchy Master Data from EXT to STG
 PARAMETERS:      NONE
 REVISION HISTORY

 Date         Name                 Comments
 -----------  -------------------  ----------------------------------------
 2022-09-02	  Shakhaf				Initial
===========================================================================*/
BEGIN
SET NOCOUNT ON


DECLARE @return_message   NVARCHAR(MAX)
DECLARE @ErrorMessage     NVARCHAR(4000)
DECLARE @ErrorProcedure   NVARCHAR(126)
DECLARE @ErrorState       INT

BEGIN TRY

       IF EXISTS ( SELECT * FROM sys.external_tables WHERE object_id = OBJECT_ID('[EXT].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER]') )
			DROP EXTERNAL TABLE   [EXT].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER]
			
       CREATE EXTERNAL TABLE   [EXT].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER]
		(              
			[Big_C] [nvarchar](200) NULL,
			[Small_C] [nvarchar](200) NULL,
			[Sub_Category] [nvarchar](200) NULL,
			[Segment] [nvarchar](200) NULL,
			[Sub_Segment] [nvarchar](200) NULL,
			[SOV] [nvarchar](200) NULL,
			[SOV_SOM] [nvarchar](200) NULL,
            [Primary_Brand] [nvarchar](200) NULL,
            [Brand] [nvarchar](200) NULL,
			[PBRT_KEY] [nvarchar](200) NULL,
			[Global_Campaign_Name] [nvarchar](200) NULL,
			[Core_MD_Supporters] [nvarchar](200) NULL,
			[Purpose_Promo_Thematic] [nvarchar](200) NULL,
            [Innovation_Renovation] [nvarchar](200) NULL,
			[Business_Group] [nvarchar](200) NULL
		)

        

       WITH (DATA_SOURCE =[adlsLocal] ,
       LOCATION = '/ProductDataStores/LiveWire/India/PBRT/Brand_Hierarchy/UL_Media_IN_PBRT_BrandHierarchy.csv',FILE_FORMAT = [ADLS_DELIMITEDTEXT],
	   REJECT_TYPE = Percentage,REJECT_VALUE = 2, REJECT_SAMPLE_VALUE=10)

	    IF EXISTS (SELECT 1 FROM sys.stats st WHERE  [NAME] = 'RPT_BRAND_HIERARCHY1')
		BEGIN
		DROP STATISTICS [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER].[RPT_BRAND_HIERARCHY1]
		DROP STATISTICS [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER].[RPT_BRAND_HIERARCHY2]
		DROP STATISTICS [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER].[RPT_BRAND_HIERARCHY3]
		DROP STATISTICS [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER].[RPT_BRAND_HIERARCHY4]
		DROP STATISTICS [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER].[RPT_BRAND_HIERARCHY5]
		DROP STATISTICS [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER].[RPT_BRAND_HIERARCHY6]
		DROP STATISTICS [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER].[RPT_BRAND_HIERARCHY7]
        DROP STATISTICS [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER].[RPT_BRAND_HIERARCHY8]
		DROP STATISTICS [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER].[RPT_BRAND_HIERARCHY9]
		DROP STATISTICS [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER].[RPT_BRAND_HIERARCHY10]
		DROP STATISTICS [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER].[RPT_BRAND_HIERARCHY11]
		DROP STATISTICS [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER].[RPT_BRAND_HIERARCHY12]
		DROP STATISTICS [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER].[RPT_BRAND_HIERARCHY13]
		DROP STATISTICS [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER].[RPT_BRAND_HIERARCHY14]
		DROP STATISTICS [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER].[RPT_BRAND_HIERARCHY15]
		END

       TRUNCATE TABLE [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER]

       INSERT INTO [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER]
	   Select *,getdate(),SYSTEM_USER,getdate(),SYSTEM_USER 
	   FROM [EXT].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER] WHERE Big_C<>'Big_C'

	    CREATE STATISTICS [RPT_BRAND_HIERARCHY1] ON [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER](Big_C)
	   CREATE STATISTICS [RPT_BRAND_HIERARCHY2] ON [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER](Small_C)
	   CREATE STATISTICS [RPT_BRAND_HIERARCHY3] ON [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER](Sub_Category)
	   CREATE STATISTICS [RPT_BRAND_HIERARCHY4] ON [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER](Segment)
	   CREATE STATISTICS [RPT_BRAND_HIERARCHY5] ON [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER](Sub_Segment)
	   CREATE STATISTICS [RPT_BRAND_HIERARCHY6] ON [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER](SOV)
	   CREATE STATISTICS [RPT_BRAND_HIERARCHY7] ON [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER](SOV_SOM)
       CREATE STATISTICS [RPT_BRAND_HIERARCHY8] ON [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER](Primary_Brand)
       CREATE STATISTICS [RPT_BRAND_HIERARCHY9] ON [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER](Brand)
	   CREATE STATISTICS [RPT_BRAND_HIERARCHY10] ON [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER](PBRT_KEY)
	   CREATE STATISTICS [RPT_BRAND_HIERARCHY11] ON [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER](Global_Campaign_Name)
	   CREATE STATISTICS [RPT_BRAND_HIERARCHY12] ON [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER](Core_MD_Supporters)
	   CREATE STATISTICS [RPT_BRAND_HIERARCHY13] ON [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER](Purpose_Promo_Thematic)
	   CREATE STATISTICS [RPT_BRAND_HIERARCHY14] ON [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER](Innovation_Renovation)
	   CREATE STATISTICS [RPT_BRAND_HIERARCHY15] ON [STG].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER](Business_Group)

	   DROP EXTERNAL TABLE  [EXT].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER]

END TRY

BEGIN CATCH
              SELECT @ErrorMessage = ISNULL(ERROR_MESSAGE(), 'Error message unavailable.'),
                @ErrorProcedure = ISNULL(ERROR_PROCEDURE(), ' [EXT].[UL_MEDIA_IN_PBRT_BRAND_HIERARCHY_MASTER_LOAD] '),
                @ErrorState = ISNULL(ERROR_STATE(), 0)
         
              SET @return_message = 'Error while Processing ' + @ErrorProcedure + ' stored procedure. Error Message: ' + @ErrorMessage;
              
              THROW 50000, @return_message, @ErrorState;
                    
END CATCH
END



GO