SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('[EXT].[UL_MEDIA_IN_CAMPAIGN_REACH_LOAD]') IS NOT NULL 
DROP PROCEDURE [EXT].[UL_MEDIA_IN_CAMPAIGN_REACH_LOAD]
GO

CREATE PROC [EXT].[UL_MEDIA_IN_CAMPAIGN_REACH_LOAD] AS
/*===========================================================================
 PROCEDURE NAME:  [EXT].[UL_MEDIA_IN_CAMPAIGN_REACH_LOAD]
 DESCRIPTION:     SP to load Brand Hierarchy Master Data from EXT to STG
 PARAMETERS:      NONE
 REVISION HISTORY

 Date         Name                 Comments
 -----------  -------------------  ----------------------------------------
 2022-09-02	  Shakhaf				Initial
===========================================================================*/
BEGIN
SET NOCOUNT ON


DECLARE @return_message   NVARCHAR(MAX)
DECLARE @ErrorMessage     NVARCHAR(4000)
DECLARE @ErrorProcedure   NVARCHAR(126)
DECLARE @ErrorState       INT

BEGIN TRY

       IF EXISTS ( SELECT * FROM sys.external_tables WHERE object_id = OBJECT_ID('[EXT].[UL_MEDIA_IN_CAMPAIGN_REACH]') )
			DROP EXTERNAL TABLE   [EXT].[UL_MEDIA_IN_CAMPAIGN_REACH]

       CREATE EXTERNAL TABLE   [EXT].[UL_MEDIA_IN_CAMPAIGN_REACH]
		(              
            [Medium] [nvarchar](200) NULL,
            [Category] [nvarchar](200) NULL,
            [Segment] [nvarchar](200) NULL,
            [Primary_Brand_Key] [nvarchar](200) NULL,
            [Month] [nvarchar](200) NULL,
            [Year] [nvarchar](200) NULL,
            [Market] [nvarchar](200) NULL,
            [Campaign] [nvarchar](200) NULL,
            [TG] [nvarchar](200) NULL,
            [LSM] [nvarchar](200) NULL,
            [Reach_Freq] [nvarchar](200) NULL,
            [Type] [nvarchar](200) NULL,
            [Value] [nvarchar](200) NULL

		)
        

       WITH (DATA_SOURCE =[adlsLocal] ,
       LOCATION = '/ProductDataStores/LiveWire/India/PBRT/Campaign_Reach/UL_Media_IN_CampaignReach.csv',FILE_FORMAT = [ADLS_DELIMITEDTEXT],
	   REJECT_TYPE = Percentage,REJECT_VALUE = 2, REJECT_SAMPLE_VALUE=10)

	    IF EXISTS (SELECT 1 FROM sys.stats st WHERE  [NAME] = 'RPT_CAMPAIGN_REACH1')
		BEGIN
		DROP STATISTICS [STG].[UL_MEDIA_IN_CAMPAIGN_REACH].[RPT_CAMPAIGN_REACH1]
		DROP STATISTICS [STG].[UL_MEDIA_IN_CAMPAIGN_REACH].[RPT_CAMPAIGN_REACH2]
		DROP STATISTICS [STG].[UL_MEDIA_IN_CAMPAIGN_REACH].[RPT_CAMPAIGN_REACH3]
		DROP STATISTICS [STG].[UL_MEDIA_IN_CAMPAIGN_REACH].[RPT_CAMPAIGN_REACH4]
		DROP STATISTICS [STG].[UL_MEDIA_IN_CAMPAIGN_REACH].[RPT_CAMPAIGN_REACH5]
		DROP STATISTICS [STG].[UL_MEDIA_IN_CAMPAIGN_REACH].[RPT_CAMPAIGN_REACH6]
		DROP STATISTICS [STG].[UL_MEDIA_IN_CAMPAIGN_REACH].[RPT_CAMPAIGN_REACH7]
        DROP STATISTICS [STG].[UL_MEDIA_IN_CAMPAIGN_REACH].[RPT_CAMPAIGN_REACH8]
		DROP STATISTICS [STG].[UL_MEDIA_IN_CAMPAIGN_REACH].[RPT_CAMPAIGN_REACH9]
		DROP STATISTICS [STG].[UL_MEDIA_IN_CAMPAIGN_REACH].[RPT_CAMPAIGN_REACH10]
		DROP STATISTICS [STG].[UL_MEDIA_IN_CAMPAIGN_REACH].[RPT_CAMPAIGN_REACH11]
		DROP STATISTICS [STG].[UL_MEDIA_IN_CAMPAIGN_REACH].[RPT_CAMPAIGN_REACH12]
		DROP STATISTICS [STG].[UL_MEDIA_IN_CAMPAIGN_REACH].[RPT_CAMPAIGN_REACH13]
		END

       TRUNCATE TABLE [STG].[UL_MEDIA_IN_CAMPAIGN_REACH]

       INSERT INTO [STG].[UL_MEDIA_IN_CAMPAIGN_REACH]
	   Select *,getdate(),SYSTEM_USER,getdate(),SYSTEM_USER 
	   FROM [EXT].[UL_MEDIA_IN_CAMPAIGN_REACH] WHERE Medium<>'Medium'

	   CREATE STATISTICS [RPT_CAMPAIGN_REACH1] ON [STG].[UL_MEDIA_IN_CAMPAIGN_REACH](Medium)
	   CREATE STATISTICS [RPT_CAMPAIGN_REACH2] ON [STG].[UL_MEDIA_IN_CAMPAIGN_REACH](Category)
       CREATE STATISTICS [RPT_CAMPAIGN_REACH3] ON [STG].[UL_MEDIA_IN_CAMPAIGN_REACH](Segment)
	   CREATE STATISTICS [RPT_CAMPAIGN_REACH4] ON [STG].[UL_MEDIA_IN_CAMPAIGN_REACH](Primary_Brand_Key)
	   CREATE STATISTICS [RPT_CAMPAIGN_REACH5] ON [STG].[UL_MEDIA_IN_CAMPAIGN_REACH](Month)
	   CREATE STATISTICS [RPT_CAMPAIGN_REACH6] ON [STG].[UL_MEDIA_IN_CAMPAIGN_REACH](Year)
	   CREATE STATISTICS [RPT_CAMPAIGN_REACH7] ON [STG].[UL_MEDIA_IN_CAMPAIGN_REACH](Market)
	   CREATE STATISTICS [RPT_CAMPAIGN_REACH8] ON [STG].[UL_MEDIA_IN_CAMPAIGN_REACH](Campaign)
       CREATE STATISTICS [RPT_CAMPAIGN_REACH9] ON [STG].[UL_MEDIA_IN_CAMPAIGN_REACH](TG)
       CREATE STATISTICS [RPT_CAMPAIGN_REACH10] ON [STG].[UL_MEDIA_IN_CAMPAIGN_REACH](LSM)
	   CREATE STATISTICS [RPT_CAMPAIGN_REACH11] ON [STG].[UL_MEDIA_IN_CAMPAIGN_REACH](Reach_Freq)
	   CREATE STATISTICS [RPT_CAMPAIGN_REACH12] ON [STG].[UL_MEDIA_IN_CAMPAIGN_REACH](Type)
	   CREATE STATISTICS [RPT_CAMPAIGN_REACH13] ON [STG].[UL_MEDIA_IN_CAMPAIGN_REACH](Value)

	   DROP EXTERNAL TABLE  [EXT].[UL_MEDIA_IN_CAMPAIGN_REACH]

END TRY

BEGIN CATCH
              SELECT @ErrorMessage = ISNULL(ERROR_MESSAGE(), 'Error message unavailable.'),
                @ErrorProcedure = ISNULL(ERROR_PROCEDURE(), ' [STG].[UL_MEDIA_IN_CAMPAIGN_REACH_LOAD] '),
                @ErrorState = ISNULL(ERROR_STATE(), 0)
         
              SET @return_message = 'Error while Processing ' + @ErrorProcedure + ' stored procedure. Error Message: ' + @ErrorMessage;
              
              THROW 50000, @return_message, @ErrorState;
                    
END CATCH
END

GO

